name: 'Greetings'

on:
  fork:
  push:
    branches: [main]
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v1
      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Hello @${{ github.actor }}! 🌟 \nThanks a bunch for creating an issue. Your input is invaluable, and we're eager to collaborate with you to address the matter. Keep up the fantastic work!"
          footer: "Don't forget to hit the :star: star button :wink:\n> [!TIP] \n> Don't forget to check our [Contributing Guidelines](https://github.com/digitomize/digitomize/blob/main/CONTRIBUTING.md), [PR Guidelines](./PR_GUIDELINES.md) and [Issue Guidelines](./Issue_GUIDELINES.md) for more details. \n\n[Website](https://digitomize.com) | [Discord](https://digitomize.com/discord) | [Twitter](https://twitter.com/intent/follow?original_referer=https://digitomize.com&screen_name=digitomize&tw_p=followbutton) | [Instagram](https://instagram.com/digitomize) | [Linkedin](https://www.linkedin.com/company/digitomize)"
